import type { Reservation } from '../types/reservation';

const STORAGE_KEY = 'foodshare_reservations_v2';

const now = Date.now();
const h = (hrs: number) => new Date(now - hrs * 3600000).toISOString();
const future = (hrs: number) => new Date(now + hrs * 3600000).toISOString();

const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'mock_res_1',
    stockId: 'inv_1',
    stockTitle: 'Fresh Organic Carrots',
    stockImage: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Vegetables',
    unit: 'kg',
    pickupLocation: 'Farm Warehouse A',
    expirationDate: future(72),
    donorId: 'donor1',
    donorName: 'Donor Company 1',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 10,
    status: 'pending',
    reservedAt: h(2),
  },
  {
    id: 'mock_res_2',
    stockId: 'inv_1',
    stockTitle: 'Fresh Organic Carrots',
    stockImage: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Vegetables',
    unit: 'kg',
    pickupLocation: 'Farm Warehouse A',
    expirationDate: future(72),
    donorId: 'donor1',
    donorName: 'Donor Company 1',
    receiverId: 'receiver2',
    receiverName: 'Receiver Shelter 2',
    quantityReserved: 5,
    status: 'donor_confirmed',
    reservedAt: h(5),
    donorConfirmedAt: h(1),
  },
  {
    id: 'mock_res_3',
    stockId: 'inv_3',
    stockTitle: 'Greek Yogurt Containers',
    stockImage: 'https://images.unsplash.com/photo-1488459716781-6f3ee109e5e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Dairy',
    unit: 'portions',
    pickupLocation: 'Cold Storage Unit B',
    expirationDate: future(168),
    donorId: 'donor1',
    donorName: 'Donor Company 1',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 8,
    status: 'completed',
    reservedAt: h(48),
    donorConfirmedAt: h(36),
    completedAt: h(24),
    quantityConfirmed: 8,
  },
  {
    id: 'mock_res_4',
    stockId: 'inv_5',
    stockTitle: 'Vegetable Stir-Fry Mix',
    stockImage: 'https://images.unsplash.com/photo-1610139901882-e2e11488d563?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Vegetables',
    unit: 'portions',
    pickupLocation: 'Freezer Section C',
    expirationDate: future(1200),
    donorId: 'donor1',
    donorName: 'Donor Company 1',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 12,
    status: 'cancelled',
    reservedAt: h(10),
    cancelledAt: h(8),
    cancelledBy: 'receiver',
  },
  {
    id: 'mock_res_5',
    stockId: 'inv_2',
    stockTitle: 'Artisan Sourdough Bread',
    stockImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Bakery',
    unit: 'pieces',
    pickupLocation: 'Central Bakery',
    expirationDate: future(4),
    donorId: 'donor2',
    donorName: 'Donor Bakery 2',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 3,
    status: 'pending',
    reservedAt: h(1),
  },
  {
    id: 'mock_res_6',
    stockId: 'inv_4',
    stockTitle: 'Mixed Berries',
    stockImage: 'https://images.unsplash.com/photo-1590721294919-c82a88798190?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Fruits',
    unit: 'boxes',
    pickupLocation: 'Cold Storage Unit A',
    expirationDate: future(5),
    donorId: 'donor2',
    donorName: 'Donor Bakery 2',
    receiverId: 'receiver2',
    receiverName: 'Receiver Shelter 2',
    quantityReserved: 4,
    status: 'donor_confirmed',
    reservedAt: h(3),
    donorConfirmedAt: h(0.5),
  },
  {
    id: 'mock_res_7',
    stockId: 'inv_6',
    stockTitle: 'Whole Wheat Pasta',
    stockImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Food',
    unit: 'kg',
    pickupLocation: 'Strada Arborilor 21, Chisinau, Moldova',
    expirationDate: future(4320),
    donorId: 'donor3',
    donorName: 'Kaufland Botanica',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 6,
    status: 'pending',
    reservedAt: h(0.5),
  },
  {
    id: 'mock_res_8',
    stockId: 'inv_5',
    stockTitle: 'Vegetable Stir-Fry Mix',
    stockImage: 'https://images.unsplash.com/photo-1610139901882-e2e11488d563?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Vegetables',
    unit: 'portions',
    pickupLocation: 'Freezer Section C',
    expirationDate: future(1200),
    donorId: 'donor1',
    donorName: 'Donor Company 1',
    receiverId: 'receiver2',
    receiverName: 'Receiver Shelter 2',
    quantityReserved: 10,
    quantityPickedUpByReceiver: 9,
    status: 'receiver_confirmed',
    reservedAt: h(6),
    donorConfirmedAt: h(4),
    receiverConfirmedAt: h(0.5),
  },

  // === donor2: one per remaining status ===
  {
    id: 'mock_res_9',
    stockId: 'inv_4',
    stockTitle: 'Mixed Berries',
    stockImage: 'https://images.unsplash.com/photo-1590721294919-c82a88798190?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Fruits',
    unit: 'boxes',
    pickupLocation: 'Bulevardul Stefan cel Mare si Sfant 83, Chisinau, Moldova',
    expirationDate: future(5),
    donorId: 'donor2',
    donorName: 'Linella Express',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 2,
    quantityPickedUpByReceiver: 2,
    status: 'receiver_confirmed',
    reservedAt: h(8),
    donorConfirmedAt: h(6),
    receiverConfirmedAt: h(1),
  },
  {
    id: 'mock_res_10',
    stockId: 'inv_2',
    stockTitle: 'Artisan Sourdough Bread',
    stockImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Bakery',
    unit: 'pieces',
    pickupLocation: 'Central Bakery',
    expirationDate: future(4),
    donorId: 'donor2',
    donorName: 'Donor Bakery 2',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 2,
    quantityConfirmed: 2,
    status: 'completed',
    reservedAt: h(72),
    donorConfirmedAt: h(60),
    receiverConfirmedAt: h(48),
    completedAt: h(47),
  },
  {
    id: 'mock_res_11',
    stockId: 'inv_2',
    stockTitle: 'Artisan Sourdough Bread',
    stockImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Bakery',
    unit: 'pieces',
    pickupLocation: 'Central Bakery',
    expirationDate: future(4),
    donorId: 'donor2',
    donorName: 'Donor Bakery 2',
    receiverId: 'receiver2',
    receiverName: 'Receiver Shelter 2',
    quantityReserved: 1,
    status: 'cancelled',
    reservedAt: h(24),
    cancelledAt: h(20),
    cancelledBy: 'donor',
  },

  // === donor3: one per remaining status ===
  {
    id: 'mock_res_12',
    stockId: 'inv_6',
    stockTitle: 'Whole Wheat Pasta',
    stockImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Food',
    unit: 'kg',
    pickupLocation: 'Dry Storage Room',
    expirationDate: future(4320),
    donorId: 'donor3',
    donorName: 'Donor Supermarket 3',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 4,
    status: 'donor_confirmed',
    reservedAt: h(3),
    donorConfirmedAt: h(1),
  },
  {
    id: 'mock_res_13',
    stockId: 'inv_6',
    stockTitle: 'Whole Wheat Pasta',
    stockImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Food',
    unit: 'kg',
    pickupLocation: 'Dry Storage Room',
    expirationDate: future(4320),
    donorId: 'donor3',
    donorName: 'Donor Supermarket 3',
    receiverId: 'receiver2',
    receiverName: 'Receiver Shelter 2',
    quantityReserved: 5,
    quantityPickedUpByReceiver: 5,
    status: 'receiver_confirmed',
    reservedAt: h(10),
    donorConfirmedAt: h(8),
    receiverConfirmedAt: h(2),
  },
  {
    id: 'mock_res_14',
    stockId: 'inv_6',
    stockTitle: 'Whole Wheat Pasta',
    stockImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Food',
    unit: 'kg',
    pickupLocation: 'Strada Puskin 32, Chisinau, Moldova',
    expirationDate: future(4320),
    donorId: 'donor3',
    donorName: 'Pegas Supermarket',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 8,
    quantityConfirmed: 7,
    status: 'completed',
    reservedAt: h(96),
    donorConfirmedAt: h(84),
    receiverConfirmedAt: h(72),
    completedAt: h(71),
  },
  {
    id: 'mock_res_16',
    stockId: 'inv_7',
    stockTitle: 'Fresh Dairy & Milk Cartons',
    stockImage: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Dairy',
    unit: 'Liters',
    pickupLocation: 'Bulevardul Dacia 31, Chisinau, Moldova',
    expirationDate: future(2),
    donorId: 'donor3',
    donorName: 'Nr1 Supermarket',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 12,
    status: 'donor_confirmed',
    reservedAt: h(2),
    donorConfirmedAt: h(0.5),
  },
  {
    id: 'mock_res_17',
    stockId: 'inv_8',
    stockTitle: 'Assorted Canned Goods',
    stockImage: 'https://images.unsplash.com/photo-1599739291060-4578e77dac5d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Canned',
    unit: 'cans',
    pickupLocation: 'Strada Alba Iulia 113, Chisinau, Moldova',
    expirationDate: future(24),
    donorId: 'donor1',
    donorName: 'Fidesco Express',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 30,
    status: 'pending',
    reservedAt: h(1),
  },
  {
    id: 'mock_res_18',
    stockId: 'inv_9',
    stockTitle: 'Lunch Menu (Catering Excess)',
    stockImage: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Meals',
    unit: 'portions',
    pickupLocation: 'Strada Alecu Russo 15, Chisinau, Moldova',
    expirationDate: future(4),
    donorId: 'donor2',
    donorName: 'Andys Pizza',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 10,
    status: 'donor_confirmed',
    reservedAt: h(3),
    donorConfirmedAt: h(1),
  },
  {
    id: 'mock_res_19',
    stockId: 'inv_10',
    stockTitle: 'Artisan Bakery Products',
    stockImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Bakery',
    unit: 'pieces',
    pickupLocation: 'Bulevardul Mircea cel Batran 24, Chisinau, Moldova',
    expirationDate: future(8),
    donorId: 'donor1',
    donorName: 'Franzeluta',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 25,
    status: 'pending',
    reservedAt: h(2),
  },
  {
    id: 'mock_res_20',
    stockId: 'inv_11',
    stockTitle: 'Fresh Vegetables & Fruits',
    stockImage: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Veggies',
    unit: 'kg',
    pickupLocation: 'Bulevardul Moscova 17, Chisinau, Moldova',
    expirationDate: future(1),
    donorId: 'donor3',
    donorName: 'Fourchette',
    receiverId: 'receiver3',
    receiverName: 'Vasilii',
    quantityReserved: 15,
    status: 'completed',
    reservedAt: h(48),
    donorConfirmedAt: h(46),
    receiverConfirmedAt: h(45),
    completedAt: h(44),
    quantityConfirmed: 15,
  },
  {
    id: 'mock_res_15',
    stockId: 'inv_6',
    stockTitle: 'Whole Wheat Pasta',
    stockImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    stockCategory: 'Cooked Food',
    unit: 'kg',
    pickupLocation: 'Dry Storage Room',
    expirationDate: future(4320),
    donorId: 'donor3',
    donorName: 'Donor Supermarket 3',
    receiverId: 'receiver1',
    receiverName: 'Receiver Charity 1',
    quantityReserved: 3,
    status: 'cancelled',
    reservedAt: h(48),
    cancelledAt: h(45),
    cancelledBy: 'receiver',
  },
];

type Listener = () => void;
const listeners = new Set<Listener>();

function load(): Reservation[] {
  try {
    const raw = typeof localStorage !== 'undefined' ? localStorage.getItem(STORAGE_KEY) : null;
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch {
    // ignore
  }
  return [...MOCK_RESERVATIONS];
}

let store: Reservation[] = load();

function persist() {
  try {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
    }
  } catch {
    // ignore
  }
}

function notify() {
  listeners.forEach((l) => l());
}

export const reservationStore = {
  getAll: (): Reservation[] => [...store],
  getById: (id: string): Reservation | undefined => store.find((r) => r.id === id),
  getByDonor: (donorId: string): Reservation[] => store.filter((r) => r.donorId === donorId),
  getByReceiver: (receiverId: string): Reservation[] => store.filter((r) => r.receiverId === receiverId),
  getByStock: (stockId: string): Reservation[] => store.filter((r) => r.stockId === stockId),
  add: (reservation: Reservation): Reservation => {
    store = [reservation, ...store];
    persist();
    notify();
    return reservation;
  },
  update: (id: string, updates: Partial<Reservation>): Reservation | undefined => {
    let updated: Reservation | undefined;
    store = store.map((r) => {
      if (r.id !== id) return r;
      updated = { ...r, ...updates };
      return updated;
    });
    persist();
    notify();
    return updated;
  },
  subscribe: (listener: Listener): (() => void) => {
    listeners.add(listener);
    return () => listeners.delete(listener);
  },
};
