// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VLM.DataAccessLayer.Context;

#nullable disable

namespace VLM.DataAccessLayer.Migrations
{
    [DbContext(typeof(VlmDbContext))]
    partial class VlmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VLM.Domain.Entities.Category.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh fruits and berries",
                            Icon = "🍎",
                            IsActive = true,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh vegetables and greens",
                            Icon = "🥦",
                            IsActive = true,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bread, pastries and baked goods",
                            Icon = "🍞",
                            IsActive = true,
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milk, cheese, yogurt and eggs",
                            Icon = "🥛",
                            IsActive = true,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prepared and cooked meals",
                            Icon = "🍲",
                            IsActive = true,
                            Name = "Cooked Food"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Comment.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 1,
                            Text = "This looks amazing! I would love to pick this up.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 1,
                            ParentCommentId = 1,
                            Text = "Thank you for your kind words! You can pick it up anytime.",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Donation.DonationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fruits",
                            CreatedDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freshly picked apples from my garden. Available for pickup.",
                            DonorId = 1,
                            ExpirationDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = "Str. Principala 12, Cluj-Napoca",
                            Quantity = 10m,
                            Status = "Available",
                            Title = "Fresh Apples",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Bakery",
                            CreatedDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freshly baked sourdough bread, 3 loaves available.",
                            DonorId = 1,
                            ExpirationDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = "Str. Principala 12, Cluj-Napoca",
                            Quantity = 3m,
                            Status = "Available",
                            Title = "Homemade Bread",
                            Unit = "pcs"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Dairy",
                            CreatedDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh whole milk from local farm. Expires in 3 days.",
                            DonorId = 3,
                            ExpirationDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = "Bd. Eroilor 5, Cluj-Napoca",
                            Quantity = 5m,
                            Status = "Reserved",
                            Title = "Milk",
                            Unit = "L"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Favorite.FavoriteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Message.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            ReceiverId = 1,
                            SenderId = 2,
                            Text = "Hi Alex! Is the milk still available for pickup tomorrow?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 12, 8, 30, 0, 0, DateTimeKind.Utc),
                            ReceiverId = 2,
                            SenderId = 1,
                            Text = "Yes, it is! You can come anytime between 8 and 12."
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 12, 8, 45, 0, 0, DateTimeKind.Utc),
                            ReceiverId = 1,
                            SenderId = 2,
                            Text = "Perfect, I'll be there at 9. Thank you!"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Notification.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maria Receiver reserved 5L of Milk from your donation.",
                            IsRead = true,
                            Link = "/reservations/1",
                            Title = "New Reservation",
                            Type = "reservation",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your reservation for Milk has been confirmed by the donor.",
                            IsRead = false,
                            Link = "/reservations/1",
                            Title = "Reservation Confirmed",
                            Type = "reservation",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh Apples are available for pickup near you.",
                            IsRead = false,
                            Link = "/donations/1",
                            Title = "New Donation Available",
                            Type = "donation",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Report.ReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DonationId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The quantity listed does not match what was available on pickup.",
                            DonationId = 2,
                            Reason = "Incorrect information",
                            ReporterId = 2,
                            Status = "pending"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Reservation.ReservationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DonorConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceiverConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            DonationId = 3,
                            DonorConfirmedAt = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "I will pick up on Friday morning.",
                            QuantityReserved = 5,
                            Status = "donor_confirmed",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Review.ReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DonorId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DonorId = 1,
                            Rating = 5,
                            ReceiverId = 2,
                            Status = "approved",
                            Text = "Alex was very generous and the food was excellent quality!"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I love helping my community by donating food.",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex@vlm.com",
                            IsActive = true,
                            Name = "Alex Donor",
                            PasswordHash = "hashed_password_1",
                            Role = "donor"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Grateful for every donation I receive.",
                            CreatedDate = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@vlm.com",
                            IsActive = true,
                            Name = "Maria Receiver",
                            PasswordHash = "hashed_password_2",
                            Role = "receiver"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Regular donor since 2025.",
                            CreatedDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@vlm.com",
                            IsActive = true,
                            Name = "John Donor",
                            PasswordHash = "hashed_password_3",
                            Role = "donor"
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptedCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasIndustrialStorage")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MissionStatement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperatingRadius")
                        .HasColumnType("integer");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedCategories = "Fruits,Vegetables,Dairy",
                            Address = "Str. Principala 12, Cluj-Napoca",
                            Description = "Local farmer donating surplus produce.",
                            HasIndustrialStorage = false,
                            Location = "Cluj-Napoca",
                            MissionStatement = "Reduce food waste in our community.",
                            OperatingHours = "Mon-Fri 8:00-18:00",
                            OperatingRadius = 15,
                            OrgName = "Alex's Farm",
                            Phone = "+40712345678",
                            TransportType = "Van",
                            UserId = 1,
                            Verified = true
                        },
                        new
                        {
                            Id = 2,
                            AcceptedCategories = "Fruits,Vegetables,Bakery,Cooked Food,Dairy",
                            Address = "Bd. Eroilor 10, Cluj-Napoca",
                            Description = "Community kitchen serving daily meals.",
                            HasIndustrialStorage = false,
                            Location = "Cluj-Napoca",
                            MissionStatement = "No one goes hungry in our neighborhood.",
                            OperatingHours = "Daily 7:00-20:00",
                            OperatingRadius = 10,
                            OrgName = "Maria's Kitchen",
                            Phone = "+40723456789",
                            TransportType = "Car",
                            UserId = 2,
                            Verified = true
                        },
                        new
                        {
                            Id = 3,
                            AcceptedCategories = "Dairy",
                            Address = "Bd. Eroilor 5, Cluj-Napoca",
                            Description = "Small local dairy farm.",
                            HasIndustrialStorage = true,
                            Location = "Cluj-Napoca",
                            MissionStatement = "Fresh dairy products for everyone.",
                            OperatingHours = "Mon-Sat 6:00-16:00",
                            OperatingRadius = 20,
                            OrgName = "John's Dairy",
                            Phone = "+40734567890",
                            TransportType = "Truck",
                            UserId = 3,
                            Verified = false
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EmailUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyPush")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifySms")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailUpdates = true,
                            NotifyEmail = true,
                            NotifyPush = true,
                            NotifySms = false,
                            Theme = "light",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EmailUpdates = false,
                            NotifyEmail = true,
                            NotifyPush = true,
                            NotifySms = true,
                            Theme = "light",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EmailUpdates = true,
                            NotifyEmail = true,
                            NotifyPush = false,
                            NotifySms = false,
                            Theme = "dark",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("VLM.Domain.Entities.Comment.CommentEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.Donation.DonationEntity", "Donation")
                        .WithMany("Comments")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLM.Domain.Entities.Comment.CommentEntity", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Donation.DonationEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Favorite.FavoriteEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.Donation.DonationEntity", "Donation")
                        .WithMany("Favorites")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Message.MessageEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Notification.NotificationEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Report.ReportEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.Donation.DonationEntity", "Donation")
                        .WithMany("Reports")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Reservation.ReservationEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.Donation.DonationEntity", "Donation")
                        .WithMany("Reservations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Receiver")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Review.ReviewEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Donor")
                        .WithMany("DonorReviews")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "Receiver")
                        .WithMany("ReceiverReviews")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserProfileEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "User")
                        .WithOne("Profile")
                        .HasForeignKey("VLM.Domain.Entities.User.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserSettingsEntity", b =>
                {
                    b.HasOne("VLM.Domain.Entities.User.UserEntity", "User")
                        .WithOne("Settings")
                        .HasForeignKey("VLM.Domain.Entities.User.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Comment.CommentEntity", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("VLM.Domain.Entities.Donation.DonationEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Reports");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("VLM.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Donations");

                    b.Navigation("DonorReviews");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("ReceiverReviews");

                    b.Navigation("Reports");

                    b.Navigation("Reservations");

                    b.Navigation("SentMessages");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
